import type { Metadata } from "next";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackClientApp } from "@/stack/client";
import { Inter } from "next/font/google";
import './globals.css'
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/shared/Sidebar";
import { ThemeProvider } from "@/components/shared/ThemeProvider";
import { ScrollProgress } from "@/components/ui/scroll-progress";
import Footer from "@/components/shared/Footer";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Punotes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} antialiased`}>
        <StackProvider app={stackClientApp}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <StackTheme>
              <SidebarProvider>
                <ScrollProgress />
                <AppSidebar />
                <SidebarInset className="p-2">
                  <SidebarTrigger className="mt-2" />
                  {children}
                  <Footer />
                </SidebarInset>
              </SidebarProvider>
            </StackTheme>
          </ThemeProvider>
        </StackProvider>
      </body>
    </html>
  );
}
